# Generated by Django 6.0 on 2025-12-29 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_remove_order_lens_order_price_order_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='title',
        ),
    ]

