# Generated by Django 6.0.2 on 2026-03-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0005_alter_order_status_alter_order_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('accepted', 'Accepted'), ('cancelled', 'Cancelled'), ('out_for_delivery', 'Out For Delivery'), ('delivered', 'Delivered'), ('partially_delivered', 'Partially Delivered')], default='pending', max_length=20),
        ),
    ]
