# Generated by Django 6.0 on 2025-12-31 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0007_companyinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyinfo',
            old_name='company_name',
            new_name='name',
        ),
    ]
    
