# Generated by Django 6.0 on 2026-01-12 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0008_rename_company_name_companyinfo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
