# Generated by Django 6.0.2 on 2026-03-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0009_alter_orderitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='refund_status',
            field=models.CharField(choices=[('none', 'None'), ('initiated', 'Refund Initiated'), ('completed', 'Refund Completed')], default='none', max_length=20),
        ),
    ]
