# Generated by Django 6.0 on 2026-02-01 09:40

from django.db import migrations, models
import django.utils.timezone




class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0010_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
