# Generated by Django 6.0.2 on 2026-03-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0010_orderitem_refund_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='return_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='return_status',
            field=models.CharField(choices=[('none', 'None'), ('requested', 'Return Requested'), ('approved', 'Return Approved'), ('rejected', 'Return Rejected'), ('completed', 'Return Completed')], default='none', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='refund_status',
            field=models.CharField(choices=[('none', 'None'), ('initiated', 'Refund Initiated'), ('completed', 'Refund Completed')], default='none', max_length=30),
        ),
    ]
