# Generated by Django 6.0 on 2026-02-01 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0011_orderitem_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='created_at',
        ),
    ]
