# Generated by Django 6.0.2 on 2026-03-07 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0015_orderitem_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='gst_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
