# Generated by Django 6.0.3 on 2026-03-11 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0016_companyinfo_gst_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='lens',
            name='power_required',
            field=models.BooleanField(default=True),
        ),
    ]
