# Generated by Django 6.0 on 2026-02-03 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryperson',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
