# Generated by Django 6.0.1 on 2026-01-27 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
