# Generated by Django 6.0.3 on 2026-03-10 15:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0016_companyinfo_gst_number'),
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('user', 'product', 'variant', 'lens_type', 'left_eye_power', 'right_eye_power')},
        ),
    ]
