# Generated by Django 6.0.3 on 2026-03-10 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_cart_unique_together_cart_lens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='lens',
        ),
    ]
