# Generated by Django 6.0 on 2026-01-27 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_product_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_active',
        ),
    ]
