# Generated by Django 6.0.3 on 2026-03-11 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_cart_lens_type_cart_lens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='lens',
        ),
        migrations.AddField(
            model_name='cart',
            name='lens_type',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('power', 'Power')], max_length=20, null=True),
        ),
    ]
