# Generated by Django 6.0.3 on 2026-03-11 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0017_lens_power_required'),
        ('app', '0006_remove_cart_lens_cart_lens_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='lens_type',
        ),
        migrations.AddField(
            model_name='cart',
            name='lens',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminpanel.lens'),
        ),
    ]
