# Generated by Django 6.0 on 2026-01-29 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_notification_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
