# Generated by Django 6.0.3 on 2026-03-11 17:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0017_lens_power_required'),
        ('app', '0007_remove_cart_lens_type_cart_lens'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('user', 'product', 'variant', 'lens', 'left_eye_power', 'right_eye_power')},
        ),
    ]
