# Generated by Django 6.0 on 2026-01-31 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
