# Generated by Django 6.0.3 on 2026-04-04 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_cart_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pincodemapping',
            name='pincode',
            field=models.CharField(max_length=6),
        ),
    ]
